package org.pocketchess.core.game;

public enum GameStatus {
    ACTIVE, CHECK, WHITE_WIN, BLACK_WIN, STALEMATE, AWAITING_PROMOTION,
    WHITE_WIN_ON_TIME, BLACK_WIN_ON_TIME, DRAW_THREEFOLD_REPETITION,
    DRAW_50_MOVES, DRAW_AGREED, WHITE_WINS_BY_RESIGNATION, BLACK_WINS_BY_RESIGNATION, DRAW_INSUFFICIENT_MATERIAL
}
